---
- name: apt-get update
  apt:
          update_cache: yes
- name: install apache2
  apt:
          name: apache2
          state: latest
- name: start apache2
  service:
          name: apache2
          state: started
# tasks file for apache2
